clear all;

nm      = 10^(-9);

lambda0min    = 380*nm;
lambda0max    = 750*nm;
lambda0points = 74;
lambda01      = lambda0min + (lambda0max-lambda0min)*[0:lambda0points]/lambda0points;

%-------------------------------------------------------------ALUMINIUM/AIR
load('Al_Air_Data.mat');
load('Air_Al_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_Air_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Al/Air max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_Air_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_Air_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_Air_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_Air_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Air_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Al/Air max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_Air_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Air_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_Air_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Air_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_Air_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Air_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Al_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%------------------------------------------------------------ALUMINIUM/ALSB
load('Al_AlSb_Data.mat');
load('AlSb_Al_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Al/AlSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_AlSb_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_AlSb_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Al/AlSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_AlSb_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_AlSb_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_AlSb_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_AlSb_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_AlSb_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_AlSb_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Al_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%-------------------------------------------------------------ALUMINIUM/ASI
load('Al_aSi_Data.mat');
load('aSi_Al_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_aSi_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Al/aSi max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_aSi_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_aSi_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_aSi_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_aSi_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Al/aSi max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_aSi_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_aSi_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_aSi_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Al_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%-------------------------------------------------------------ALUMINIUM/GAP
load('Al_GaP_Data.mat');
load('GaP_Al_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_GaP_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Al/GaP max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_GaP_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_GaP_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_GaP_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_GaP_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Al/GaP max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_GaP_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_GaP_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_GaP_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Al_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%------------------------------------------------------------ALUMINIUM/GASB
load('Al_GaSb_Data.mat');
load('GaSb_Al_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_GaSb_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Al/GaSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_GaSb_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_GaSb_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_GaSb_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_GaSb_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Al/GaSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_GaSb_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_GaSb_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_GaSb_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Al_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%--------------------------------------------------------------ALUMINIUM/GE
load('Al_Ge_Data.mat');
load('Ge_Al_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_Ge_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Al/Ge max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_Ge_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_Ge_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_Ge_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_Ge_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Al/Ge max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_Ge_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_Ge_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_Ge_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Al_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%------------------------------------------------------------ALUMINIUM/INAS
load('Al_InAs_Data.mat');
load('InAs_Al_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_InAs_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Al/InAs max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_InAs_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_InAs_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_InAs_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Al_InAs_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Al/InAs max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_InAs_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Al_InAs_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Al_InAs_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Al_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);