clear all;

nm      = 10^(-9);

lambda0min    = 380*nm;
lambda0max    = 750*nm;
lambda0points = 74;
lambda01      = lambda0min + (lambda0max-lambda0min)*[0:lambda0points]/lambda0points;

load('Ag_AlSb_Data.mat');
load('Ag_aSi_Data.mat');
load('Ag_GaP_Data.mat');
load('Ag_GaSb_Data.mat');
load('Ag_Ge_Data.mat');
load('Ag_InAs_Data.mat');

load('Al_AlSb_Data.mat');
load('Al_aSi_Data.mat');
load('Al_GaP_Data.mat');
load('Al_GaSb_Data.mat');
load('Al_Ge_Data.mat');
load('Al_InAs_Data.mat');

load('Au_AlSb_Data.mat');
load('Au_aSi_Data.mat');
load('Au_GaP_Data.mat');
load('Au_GaSb_Data.mat');
load('Au_Ge_Data.mat');
load('Au_InAs_Data.mat');

load('Ti_AlSb_Data.mat');
load('Ti_aSi_Data.mat');
load('Ti_GaP_Data.mat');
load('Ti_GaSb_Data.mat');
load('Ti_Ge_Data.mat');
load('Ti_InAs_Data.mat');

%--------------------------------------------------------------------PTEabs
figure;
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTEabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_PmaxTEabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_PmaxTEabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_PmaxTEabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_PmaxTEabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_PmaxTEabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{abs}/P^{TE}_{0,abs}');
title('Gold-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTEabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_PmaxTEabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_PmaxTEabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_PmaxTEabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_PmaxTEabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_PmaxTEabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{abs}/P^{TE}_{0,abs}');
title('Aluminum-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTEabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_PmaxTEabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_PmaxTEabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_PmaxTEabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_PmaxTEabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_PmaxTEabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{abs}/P^{TE}_{0,abs}');
title('Silver-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ti_AlSb_PmaxTEabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_aSi_PmaxTEabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaP_PmaxTEabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaSb_PmaxTEabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_Ge_PmaxTEabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_InAs_PmaxTEabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{abs}/P^{TE}_{0,abs}');
title('Titanium-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);

%--------------------------------------------------------------------PTMabs
figure;
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTMabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_PmaxTMabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_PmaxTMabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_PmaxTMabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_PmaxTMabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_PmaxTMabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{abs}/P^{TM}_{0,abs}');
title('Gold-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTMabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_PmaxTMabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_PmaxTMabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_PmaxTMabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_PmaxTMabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_PmaxTMabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{abs}/P^{TM}_{0,abs}');
title('Aluminum-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTMabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_PmaxTMabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_PmaxTMabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_PmaxTMabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_PmaxTMabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_PmaxTMabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{abs}/P^{TM}_{0,abs}');
title('Silver-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ti_AlSb_PmaxTMabs,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_aSi_PmaxTMabs,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaP_PmaxTMabs,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaSb_PmaxTMabs,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_Ge_PmaxTMabs,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_InAs_PmaxTMabs,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{abs}/P^{TM}_{0,abs}');
title('Titanium-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);

%-------------------------------------------------------------------PTEscat
figure;
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTEscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_PmaxTEscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_PmaxTEscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_PmaxTEscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_PmaxTEscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_PmaxTEscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{scat}/P^{TE}_{0,scat}');
title('Gold-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTEscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_PmaxTEscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_PmaxTEscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_PmaxTEscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_PmaxTEscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_PmaxTEscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{scat}/P^{TE}_{0,scat}');
title('Aluminum-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTEscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_PmaxTEscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_PmaxTEscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_PmaxTEscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_PmaxTEscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_PmaxTEscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{scat}/P^{TE}_{0,scat}');
title('Silver-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ti_AlSb_PmaxTEscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_aSi_PmaxTEscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaP_PmaxTEscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaSb_PmaxTEscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_Ge_PmaxTEscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_InAs_PmaxTEscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TE}_{scat}/P^{TE}_{0,scat}');
title('Titanium-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);

%-------------------------------------------------------------------PTMscat
figure;
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTMscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_PmaxTMscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_PmaxTMscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_PmaxTMscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_PmaxTMscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_PmaxTMscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{scat}/P^{TM}_{0,scat}');
title('Gold-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Al_AlSb_PmaxTMscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_aSi_PmaxTMscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaP_PmaxTMscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Al_GaSb_PmaxTMscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Al_Ge_PmaxTMscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Al_InAs_PmaxTMscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{scat}/P^{TM}_{0,scat}');
title('Aluminum-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTMscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_PmaxTMscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_PmaxTMscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_PmaxTMscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_PmaxTMscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_PmaxTMscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{scat}/P^{TM}_{0,scat}');
title('Silver-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ti_AlSb_PmaxTMscat,  '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_aSi_PmaxTMscat,   '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaP_PmaxTMscat,   '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_GaSb_PmaxTMscat,  '-ko', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_Ge_PmaxTMscat,    '-mo', 'LineWidth', 2.1);
plot(lambda01/nm, Ti_InAs_PmaxTMscat,  '-co', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
ylabel('P^{TM}_{scat}/P^{TM}_{0,scat}');
title('Titanium-based Designs');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);