clear all;

nm      = 10^(-9);

lambda0min    = 380*nm;
lambda0max    = 750*nm;
lambda0points = 74;
lambda01      = lambda0min + (lambda0max-lambda0min)*[0:lambda0points]/lambda0points;

%--------------------------------------------------------------GOLD/AIR
load('Au_Air_Data.mat');
load('Air_Au_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_Air_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Au/Air max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_Air_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_Air_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_Air_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_Air_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Air_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Au/Air max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_Air_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Air_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_Air_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Air_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_Air_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Air_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Au_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%-------------------------------------------------------------GOLD/ALSB
load('Au_AlSb_Data.mat');
load('AlSb_Au_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Au/AlSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_AlSb_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_AlSb_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_AlSb_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Au/AlSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_AlSb_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_AlSb_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_AlSb_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_AlSb_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_AlSb_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_AlSb_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Au_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%--------------------------------------------------------------GOLD/ASI
load('Au_aSi_Data.mat');
load('aSi_Au_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_aSi_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Au/aSi max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_aSi_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_aSi_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_aSi_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_aSi_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Au/aSi max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_aSi_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_aSi_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_aSi_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_aSi_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Au_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%--------------------------------------------------------------GOLD/GAP
load('Au_GaP_Data.mat');
load('GaP_Au_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_GaP_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Au/GaP max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_GaP_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_GaP_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_GaP_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_GaP_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Au/GaP max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_GaP_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_GaP_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_GaP_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaP_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Au_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%-------------------------------------------------------------GOLD/GASB
load('Au_GaSb_Data.mat');
load('GaSb_Au_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_GaSb_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Au/GaSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_GaSb_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_GaSb_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_GaSb_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_GaSb_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Au/GaSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_GaSb_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_GaSb_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_GaSb_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_GaSb_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Au_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%---------------------------------------------------------------GOLD/GE
load('Au_Ge_Data.mat');
load('Ge_Au_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_Ge_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Au/Ge max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_Ge_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_Ge_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_Ge_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_Ge_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Au/Ge max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_Ge_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_Ge_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_Ge_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_Ge_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Au_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%-------------------------------------------------------------GOLD/INAS
load('Au_InAs_Data.mat');
load('InAs_Au_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_InAs_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Au/InAs max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_InAs_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_InAs_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_InAs_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Au_InAs_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Au/InAs max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Au_InAs_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Au_InAs_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Au_InAs_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Au_InAs_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Au_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);