clear all;

nm      = 10^(-9);

lambda0min    = 380*nm;
lambda0max    = 750*nm;
lambda0points = 74;
lambda01      = lambda0min + (lambda0max-lambda0min)*[0:lambda0points]/lambda0points;

%----------------------------------------------------------------SILVER/AIR
load('Ag_Air_Data.mat');
load('Air_Ag_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_Air_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Ag/Air max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_Air_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_Air_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_Air_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_Air_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Air_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Ag/Air max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_Air_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Air_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_Air_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Air_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_Air_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Air_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Air_Ag_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%---------------------------------------------------------------SILVER/ALSB
load('Ag_AlSb_Data.mat');
load('AlSb_Ag_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Ag/AlSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_AlSb_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_AlSb_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_AlSb_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Ag/AlSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_AlSb_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_AlSb_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_AlSb_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_AlSb_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_AlSb_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_AlSb_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, AlSb_Ag_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%----------------------------------------------------------------SILVER/ASI
load('Ag_aSi_Data.mat');
load('aSi_Ag_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_aSi_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Ag/aSi max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_aSi_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_aSi_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_aSi_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_aSi_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Ag/aSi max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_aSi_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_aSi_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_aSi_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_aSi_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, aSi_Ag_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%----------------------------------------------------------------SILVER/GAP
load('Ag_GaP_Data.mat');
load('GaP_Ag_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_GaP_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Ag/GaP max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_GaP_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_GaP_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_GaP_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_GaP_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Ag/GaP max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_GaP_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_GaP_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_GaP_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaP_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaP_Ag_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%---------------------------------------------------------------SILVER/GASB
load('Ag_GaSb_Data.mat');
load('GaSb_Ag_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_GaSb_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Ag/GaSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_GaSb_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_GaSb_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_GaSb_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_GaSb_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Ag/GaSb max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_GaSb_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_GaSb_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_GaSb_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_GaSb_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, GaSb_Ag_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%-----------------------------------------------------------------SILVER/GE
load('Ag_Ge_Data.mat');
load('Ge_Ag_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_Ge_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Ag/Ge max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_Ge_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_Ge_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_Ge_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_Ge_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Ag/Ge max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_Ge_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_Ge_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_Ge_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_Ge_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, Ge_Ag_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);

%---------------------------------------------------------------SILVER/INAS
load('Ag_InAs_Data.mat');
load('InAs_Ag_Data.mat');
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_InAs_PmaxTEabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_PmaxTEabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('Ag/InAs max P^{TE}_{abs}/P^{TE}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_InAs_PmaxTMabs, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_PmaxTMabs, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_InAs_PmaxTEscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_PmaxTEscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_InAs_PmaxTMscat, '-bo', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_PmaxTMscat, '-mo', 'LineWidth', 1.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
xlim([400, 700]); ylim([1, 3]);
figure;
subplot(2, 2, 1);
hold;
plot(lambda01/nm, Ag_InAs_aoboptTEabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_boloptTEabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_aoboptTEabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_boloptTEabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('Ag/InAs max P^{TE}_{abs}/P^{TE}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 2);
hold;
plot(lambda01/nm, Ag_InAs_aoboptTMabs, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_boloptTMabs, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_aoboptTMabs, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_boloptTMabs, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{abs}/P^{TM}_{0,abs}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 3);
hold;
plot(lambda01/nm, Ag_InAs_aoboptTEscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_boloptTEscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_aoboptTEscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_boloptTEscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TE}_{scat}/P^{TE}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);
subplot(2, 2, 4);
hold;
plot(lambda01/nm, Ag_InAs_aoboptTMscat, '-go', 'LineWidth', 2.1);
plot(lambda01/nm, Ag_InAs_boloptTMscat, '-ro', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_aoboptTMscat, '-co', 'LineWidth', 2.1);
plot(lambda01/nm, InAs_Ag_boloptTMscat, '-mo', 'LineWidth', 2.1);
xlabel('\lambda_0 (nm)');
title('max P^{TM}_{scat}/P^{TM}_{0,scat}');
legend('a/b', 'b/\lambda_0');
grid;
xlim([lambda0min/nm, lambda0max/nm]);